# Generated by Django 4.2.26 on 2025-11-20 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ideas', '0002_alter_comment_options_alter_comment_idea_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du Poste de Police')),
                ('quartier', models.CharField(max_length=100, verbose_name='Quartier')),
                ('commune', models.CharField(max_length=100, verbose_name='Commune')),
                ('emergency_number', models.CharField(max_length=20, verbose_name="Numéro d'Urgence")),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='police_stations', to='accounts.district', verbose_name='Circonscription')),
            ],
            options={
                'verbose_name': 'Poste de Police',
                'verbose_name_plural': 'Postes de Police',
            },
        ),
    ]
