# Generated by Django 4.2.26 on 2025-11-20 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ideas', '0003_policestation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Nom de l'Hôpital")),
                ('quartier', models.CharField(max_length=100, verbose_name='Quartier')),
                ('commune', models.CharField(max_length=100, verbose_name='Commune')),
                ('emergency_number', models.CharField(max_length=20, verbose_name="Numéro d'Urgence")),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to='accounts.district', verbose_name='Circonscription')),
            ],
            options={
                'verbose_name': 'Hôpital de Référence',
                'verbose_name_plural': 'Hôpitaux de Référence',
            },
        ),
    ]
